version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    depends_on:
      - db
    image: evashokom/foodgram_backend
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/app/media

  frontend:
    container_name: foodgram-front
    image: evashokom/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    container_name: foodgram-proxy
    depends_on:
      - backend
      - frontend
    image: evashokom/foodgram_gateway
    ports:
      - "8888:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles
      - media:/media
