version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    depends_on:
      - db
    build: ./backend/
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/app/media

  frontend:
    container_name: foodgram-front
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  nginx:
    container_name: foodgram-proxy
    depends_on:
      - backend
      - frontend
    image: nginx:1.25.4-alpine
    ports:
      - "8888:80"
    volumes:
      - static:/staticfiles
      - media:/media
      - ../docs/:/usr/share/nginx/html/api/docs/
