# Generated by Django 3.2.16 on 2024-05-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='full_url',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
