# Generated by Django 3.2.16 on 2024-05-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortner', '0002_auto_20240519_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='full_url',
            field=models.CharField(max_length=128),
        ),
    ]
