# Generated by Django 3.2.16 on 2024-05-07 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20240507_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, help_text='Укажите необходимое количество ингредиента для рецепта', validators=[django.core.validators.MinValueValidator(1, 'Минимальное количество для ингредиента - 1'), django.core.validators.MaxValueValidator(5000, 'Максимальное количество для ингредиента - 5000')], verbose_name='Количество ингредиента'),
        ),
    ]
